### ISSUE TITLE
Feature Request - No outside gutters

### ISSUE THREAD

**Issue by louiesolomon** [praneshr/guidemate#3]
I'd like to be able to create a grid with no gutters on the first and last columns (similar to how http://gridcalculator.dk/ works when you set margin to 0). Thanks!

**Comment by corysimmons** [comment]
Agreed. This is close to being a really amazing plugin (looks great and is really useful) but there are a few hiccups like gutters on the outside of a grid shouldn't exist (especially when there is already a way to add those via the margin settings).

The problem is around https://github.com/praneshr/guidemate/blob/ea383819464499b00a61b89d6134a4265cf328c2/src/plugin.ts#L131-L159

@louiesolomon In the meantime, you can create a Layout Grid:

![image](https://user-images.githubusercontent.com/224636/81601283-a45b9980-9398-11ea-9d86-ddd97a314f08.png)

**Comment by praneshr** [comment]
@louiesolomon Can you provide a screenshot of the problem? Currently, you can set the `margin` as 0 in the plugin to achieve the same.
